# Generated by Django 3.2.2 on 2021-06-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagescrapperapp', '0002_alter_scrapedimage_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedimage',
            name='image_url',
            field=models.CharField(max_length=10000),
        ),
    ]
